version: "3.3"

services:
  nginx:
    image: nginx
    pull_policy: never
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  wordpress:
    image: wordpress
    pull_policy: never
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp_data:/var/www/
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    pull_policy: never
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  static_website:
    image: static_website
    pull_policy: never
    container_name: static_website
    build: requirements/bonus/static_website
    networks:
      - inception_network
    restart: always

  adminer:
    image: adminer
    pull_policy: never
    container_name: adminer
    build: requirements/bonus/adminer
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: always

  redis:
    image: redis
    pull_policy: never
    container_name: redis
    build: requirements/bonus/redis
    networks:
      - inception_network
    restart: always

  ftp:
    image: ftp
    pull_policy: never
    container_name: ftp
    build: requirements/bonus/ftp
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/content
    networks:
      - inception_network
    env_file:
      - .env

  liman:
    image: liman
    pull_policy: never
    container_name: liman
    build: requirements/bonus/liman
    ports:
      - "5000:5000"
    networks:
      - inception_network
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - liman:/liman/data
  
volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/zlafou/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/zlafou/data/mariadb
      o: bind
  liman:

networks:
  inception_network:
    driver: bridge
    