version: "3.3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp_data:/var/www/
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  static_website:
    container_name: static_website
    build: requirements/bonus/static_website
    networks:
      - inception_network
    restart: always

  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: always

  redis:
    container_name: redis
    build: requirements/bonus/redis
    networks:
      - inception_network
    restart: always

  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/content
    networks:
      - inception_network
    env_file:
      - .env

  liman:
    container_name: liman
    build: requirements/bonus/liman
    ports:
      - "5000:5000"
    networks:
      - inception_network
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - liman:/liman/data
  
volumes:
  wp_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/zlafou/incep_data/wordpress
    #   o: bind
  db_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/zlafou/incep_data/mariadb
    #   o: bind
  liman:

networks:
  inception_network:
    driver: bridge
    