version: "3.3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/
    depends_on:
      - wordpress
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp_data:/var/www/
    networks:
      - inception_network
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  static_website:
    container_name: static_website
    build: requirements/bonus/static_website
    restart: always
    networks:
      - inception_network

  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    restart: always
    networks:
      - inception_network
  
volumes:
  wp_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/zlafou/incep_data/wordpress
    #   o: bind
  db_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /Users/zlafou/incep_data/mariadb
    #   o: bind

networks:
  inception_network:
    driver: bridge
    