FROM debian:buster

#install meriaDB
RUN apt update -y && apt install -y mariadb-server

#copy mariadb config file
# COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d

#copy mariadb init script
COPY ./tools/init_db.sh /tmp/init_db.sh

#give execution rights
RUN chmod +x /tmp/init_db.sh

#runing the script
CMD [ "/tmp/init_db.sh" ]