FROM debian:buster

RUN apt update -y && apt install -y php php-mysqli default-mysql-client php-mysql wget

RUN wget "https://www.adminer.org/latest.php" -O /var/www/html/adminer.php

RUN chmod +x /var/www/html/adminer.php

WORKDIR /var/www/html

CMD [ "php", "-S", "0.0.0.0:8080" ]