FROM debian:buster

#install nginx and openssl
RUN apt-get update && apt-get install -y nginx openssl

#generate self-signed certificate
RUN openssl req -x509 -days 365 -nodes -newkey rsa:2048 -keyout /etc/ssl/private/selfsigned.key -out /etc/ssl/certs/selfsigned.crt -subj "/CN=zlafou.42.fr"

#copy nginx config file
COPY utils/nginx.conf /etc/nginx/conf.d/nginx.conf

#start nginx
CMD [ "nginx" , "-g" , "daemon off;" ]